{% set name = 'ctgan' %}
{% set version = '0.5.2.dev0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - packaging >=20,<22
    - python >=3.6,<3.10
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - scikit-learn >=0.24,<1
    - pytorch >=1.8.0,<2
    - torchvision >=0.9.0,<1
    - rdt >=0.6.2,<0.7
  run:
    - packaging >=20,<22
    - python >=3.6,<3.10
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - scikit-learn >=0.24,<1
    - pytorch >=1.8.0,<2
    - torchvision >=0.9.0,<1
    - rdt >=0.6.2,<0.7

about:
  home: "https://github.com/sdv-dev/CTGAN"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Conditional GAN for Tabular Data"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - sdv-dev
